### ISSUE TITLE
Make default image with 360px width optional

### ISSUE THREAD

**Issue by alexanderschnitzler** [alexanderschnitzler/fluid-styled-responsive-images#11]
The idea of a small default image is still a good solution when working with polyfills, but it does not allow to render images smaller than 360px properly, like icons.

Therefore the default image should be optional, but enabled by default to not be breaking.

**Comment by Toccamonium** [comment]
Hi Alex,
do you have an example config for this switch? Because with the old one you posted here, it's not working properly anymore. Thanks indeed.
