### ISSUE TITLE
What i am missing?

### ISSUE THREAD

**Issue by timofo** [alexanderschnitzler/fluid-styled-responsive-images#12]
i have installed the extension and included the static template after fluid styled content.

`tt_content.textmedia.settings.responsive_image_rendering.sourceCollection {
  medium {
    width = 720m
    srcset = 720w
    sizes = 100vw
  }
  large {
    width = 940m
    srcset = 940w
    sizes = 100vw
  }
  bigger {
    width = 1140m
    srcset = 1140w
    sizes = 100vw
  }
}
`
this is my testcode. But my images are missing the srcset attribute?
I am missing something?

edit:
if i make a var_dump of $this in function buildImageTag then i see that srcset is empty. But you can see my typoscript. srcset ist set. 

if i write a throw exception instead of continue in processSourceCollection, then i get a:
RuntimeException thrown in file
ext/fluid_styled_responsive_images/Classes/Resource/Rendering/ImageRenderer.php in line 191.
if ((int)$sourceCollection['width'] > (int)$this->defaultWidth) {

What does it mean?
How is the width (default width) calculated?

only works if i set 
`styles.content.textmedia.maxW = 10000
styles.content.textmedia.maxWInText = 10000
`

**Comment by alexanderschnitzler** [comment]
This seems to be the same issue like in #13.

> I guess the actual image width is smaller than the one you want to generate. Then it doesn't make sense processing an image. It's possible to downscale an image, but you can't properly upscale it.
> 
> Please have a look at the image width.

**Comment by alexanderschnitzler** [comment]
If this ticket is still relevant, feel free to reopen.
