### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by cedricziel** [alexanderschnitzler/fluid-styled-responsive-images#14]
I'd be glad if you could release a new version with the changes for the attributes.

Cheers!

**Comment by alexanderschnitzler** [comment]
Sorry, but I am really having a lot of stress lately. Wanted to create a documentation before releasing the next version but I guess I will simply skip that just to get things going...

**Comment by cedricziel** [comment]
If I had to choose between documentation and release - I'd choose release.

Sorry for putting more load on you :/

**Comment by alexanderschnitzler** [comment]
Just pushed a new version to TER. Also pushed all the changes to github but it seems github itself is a bit slow updating this repository.

**Comment by cedricziel** [comment]
Great - thanks a lot!
