### ISSUE TITLE
Problem with jpg image size of the src image

### ISSUE THREAD

**Issue by Toccamonium** [alexanderschnitzler/fluid-styled-responsive-images#15]
Hi Alex,

perhaps I miss something, but when installing your extension, I have a problem with the jpg images in the img-src. They are included in the original size I uploaded them - frontend and backend. PNG is fine. Anyway as you mentioned, actually the src should be 360px. Any suggestions, what could cause this? 
Additional info: jpg are rendered smaller, when I use them in a text/media element with text. Just an image without text, it's getting that large.
Page jpg image without text: https://www.sineos.de/
Page jpg image with text: https://www.sineos.de/loesungen/

**Comment by cedricziel** [comment]
Please refrain from cold-mailing contributors. - Especially when you're opening a ticket anyways.

**Comment by alexanderschnitzler** [comment]
I guess your problem is that your image has a comma in its name, so the browser doesn't know where to split the `srcset` properly. The image on https://www.sineos.de/loesungen/ looks fine to me, what's the problem with that?

**Comment by Toccamonium** [comment]
The image "Frankfurt Skyline" with the comma works properly. This part is just an HTML element, the code produced by the RWD image generator.

The problem is for instance the jpg image beside the title "Aktuelles Projekt: Fitness-Treff Orscholz" (https://is.gd/uXMIOT) or the jpg on this page https://www.sineos.de/index.php?id=11 
Click on the image and select "Grafik anzeigen" > it links to the direct upload folder and not to the "_processed_" folder, like it's on this page for the png graphic https://www.sineos.de/services/content-marketing/social-media-strategie/

The question is, why does it not get the _processed_ path for jpgs?

**Comment by alexanderschnitzler** [comment]
I'm sorry but I don't have a clue what happens there. Can you please paste the typoscript configuration? There is definitely no distinction between png and jpg files. The only important attribute is the image width. Also, please tell me which version of the extension you are using.

**Comment by Toccamonium** [comment]
I updated to version 1.2.0 and switched to this TS code snippet:

```
tt_content.textmedia.settings.responsive_image_rendering {
    layoutKey = srcset
    sourceCollection {
        10 {
            width = 1140m
            srcset = 1140w
        }

        20 {
            width = 720m
            srcset = 720w
            sizes = (min-width: 1025px) 660px
        }

        30 {
            width = 640m
            srcset = 640w
        }

        40 {
            width = 360m
            srcset = 360w
        }

        50 {
            width = 320m
            srcset = 320w
            sizes = calc(100vw - 30px)
        }
    }
}
```

png is catched from _processed_, jpg still from fileadmin/user_upload.

**Comment by alexanderschnitzler** [comment]
Well, the configuration looks fine. I can't help you any further with that. Maybe you found a bug I don't know. Can you debug that with xdebug? Processing of files is not done by my extension, so I guess there is something else fishy. Maybe your image dimensions are wrong in sys_file...

**Comment by Toccamonium** [comment]
Thx for input. I tried the extension on another TYPO3 7.6 version with different output. I will test it on a fresh installation within the next days and let you know.

**Comment by Toccamonium** [comment]
Info: As I wrote yesterday, I setup a new TYPO3 instance for testing, just with the basic extensions. And here everything is working properly - no distinction between png and jpg. So must be another extension or whatever, which interferes here.
