### ISSUE TITLE
Aus einem 25 KB Bild wird eine über 1 MB große Datei

### ISSUE THREAD

**Issue by ProWebs** [alexanderschnitzler/fluid-styled-responsive-images#23]
Die original Bilddateien sind Web optimiert und sehr klein, leider werden in der mobilen Ansicht auf einmal echte Brocken bereit gestellt.

Google PageSpeed meckert hier mit recht an:

Bilder optimieren
Durch eine korrekte Formatierung und Komprimierung von Bildern können viele Datenbytes gespart werden.
Optimieren Sie die folgenden Bilder, um ihre Größe um 5 MB (90 %) zu reduzieren.

    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…2015_auszeichnung_200x292_70b788cac4.png könnten 1,1 MB (83 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…/csm_Proven-Expert-Siegel_27823161a5.png könnten 1.001,7 KB (94 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…ochzeitsfotograf-in-Essen_275d6c8271.jpg könnten 551,3 KB (97 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…er-Fotoshooting-im-Studio_89670606db.jpg könnten 542,9 KB (98 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…2016_auszeichnung_200x349_7e8bcb72f2.png könnten 525,8 KB (76 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…-Bewerbungsfotos-in-Essen_f31328a687.jpg könnten 314,1 KB (97 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…uesseldorf-Dortmund-Koeln_6a89fac050.jpg könnten 284,9 KB (98 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…Teaser-Businessfotografie_c1c1235add.jpg könnten 260,4 KB (98 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…0/8/csm_Teaser-Imagefilme_a500b45553.jpg könnten 231,5 KB (98 %) eingespart werden.
    Durch die Komprimierung und Größenanpassung von http://www.digitale-fotografien.com/…sm_Teaser-Eventfotografie_20c281191d.jpg könnten 224,7 KB (98 %) eingespart werden.
    Durch die Komprimierung von http://www.digitale-fotografien.com/…otografie-Security-2016-1_d46482fa20.jpg könnten 2,8 KB (39 %) eingespart werden.
    Durch die Komprimierung von http://www.digitale-fotografien.com/…1/csm_ETB-Wohnbau-Baskets_670908b863.jpg könnten 944 Byte (17 %) eingespart werden.
    Durch die Komprimierung von http://www.digitale-fotografien.com/…logo-mitglied-im-dpv-grau_1486dd3323.jpg könnten 727 Byte (12 %) eingespart werden.

**Comment by cedricziel** [comment]
Hi @ProWebs. Thank you for your report. You might want to get a little more into detail regarding your configuration and system environment. Thx.

**Comment by alexanderschnitzler** [comment]
@ProWebs If you are still interested in this issue, feel free to reopen it but for now I will close it.

This extension doesn't work the way you want it to work. You use the biggest image available in your elements and this extension generates the small versions. If you have an optimized image and you let it be rendered again by TYPO3, chances are high that you will bigger images than the original. There's not much you can do.
