### ISSUE TITLE
Fluid f:image and srcset

### ISSUE THREAD

**Issue by ghost** [alexanderschnitzler/fluid-styled-responsive-images#25]
Hello,

when I use the MASK Extension and within a template file the f:image view helper there is no srcset render.

Can I activate it there or it is not possible ?

Greetings.

**Comment by cedricziel** [comment]
It's perfectly possible, though by design this only happens if you use the `<f:media` ViewHelper - as stated in the README (https://github.com/alexanderschnitzler/fluid-styled-responsive-images#usage)

Let me know if you run into any problems.

**Comment by ghost** [comment]
With f:media I don't get sourcesets. Is that a problem with sorting extension libs ?

**Comment by ghost** [comment]
I get not sourcesets.

**Comment by ghost** [comment]
`<f:media file="{file}" alt="{file.alternative}" title="{file.title}" data="{description: file.description}" class="img-responsive lazyload"/>`

**Comment by ghost** [comment]
no srcset in output

**Comment by cedricziel** [comment]
what is your typoscript configuration?

**Comment by ghost** [comment]
Hello,

when I use text & media content element all works correct.

Here is the typoscript configuration:

```
tt_content {
    textmedia {
        settings {
            image_classes = {$styles.content.textmedia.imageClasses}
            responsive_image_rendering {
                layoutKey = srcset

                # Default Breakpoints
                sourceCollection {
                    xl {
                        width = 1200
                        srcset = 1200w
                    }

                    lg {
                        width = 992
                        srcset = 992w
                    }

                    md {
                        width = 768
                        srcset = 768w
                    }

                    sm {
                        width = 480
                        srcset = 480w
                    }

                    xs {
                        width = 320
                        srcset = 320w
                        sizes = auto
                    }
                }
            }

            origo < tx_origo
        }
    }
}

```

**Comment by cedricziel** [comment]
I'll try to reproduce it myself.

Can you tell me the version numbers you use (TYPO3, mask, fsri)?

**Comment by ghost** [comment]
TYPO3 7.6.16
MASK 2.1.1
FSRI 1.2.0

Thanks.

**Comment by ghost** [comment]
Loading Order:

Fluid
FSRI
Mask

**Comment by ghost** [comment]
Do you test it ?
