### ISSUE TITLE
Image file size PNG

### ISSUE THREAD

**Issue by Toccamonium** [alexanderschnitzler/fluid-styled-responsive-images#31]
Hi,

How can this be fixed: I uploaded a png file in text & media. The original file was optimized to 50 kb. Now when it gets processed with f-s-r-images it has 113 kb. Google pagespeed was bringing up this issue. What do I have to do, that the image size isn't getting bigger?

Thx, Florian

**Comment by alexanderschnitzler** [comment]
This cannot really be fixed right away. If you have an optimized image, TYPO3 will process it and generate new ones that do not have the optimizations.

But it would be a good idea to integrate things like imageoptim or such into either the core or this extension. However, it's currently not planned. :/

**Comment by Toccamonium** [comment]
Thanks for reply. We are using the extension tinypng from Alessandro Schmitz. This extension reduces all files perfectly. But this process should be integrated into/after the TYPO3 image processing and everything would be cool :)
