### ISSUE TITLE
8LTS: Don't touch TCA in ext_tables.php

### ISSUE THREAD

**Issue by whiteroom** [alexanderschnitzler/fluid-styled-responsive-images#35]
TCA changes within ext_tables.php can be moved to Configuration/TCA since core 6.2

Please update:

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile(
    'fluid_styled_responsive_images',
    'Configuration/TypoScript',
    'Fluid Styled Responsive Images'
);

has to go to /Configuration/TCA/Overrides/sys_template.php

**Comment by alexanderschnitzler** [comment]
Can you do a pull request for that?
