### ISSUE TITLE
Use typo3/cms-core as dependency

### ISSUE THREAD

**Issue by spoonerWeb** [alexanderschnitzler/fluid-styled-responsive-images#38]
For using the subtree split and composer the dependency must be changed from `typo3/cms` to `typo3/cms-core`.
See: https://usetypo3.com/typo3-subtree-split-and-composer.html

**Comment by spoonerWeb** [comment]
Would be nice to release a version for 8.7.x as well with this change.

**Comment by alexanderschnitzler** [comment]
A new version for 8.7. has been released.
