### ISSUE TITLE
set alt and title from merged properties

### ISSUE THREAD

**Issue by thomaskieslich** [alexanderschnitzler/fluid-styled-responsive-images#4]
$this->tagBuilder->addAttribute('alt', $file->getProperty('alternative'));
$this->tagBuilder->addAttribute('title', $file->getProperty('title'));

Set alt and title from filereference too.

**Comment by alexanderschnitzler** [comment]
Sorry Thomas,
I didn't get notified by github about that issue.

Will see that I can push a new release soon.
