### ISSUE TITLE
[9.5 LTS] class="image-embed-item"

### ISSUE THREAD

**Issue by xerc** [alexanderschnitzler/fluid-styled-responsive-images#40]
`<img class="image-embed-item"` is missing/ignored

**Comment by alexanderschnitzler** [comment]
Hi @xerc,
sorry for the late answer. This extension is unmaintained for months now and there won't be any updates in the future.

If you are interested in using this extension as a base for a custom product, feel free to fork.
There are too many different extensions taking care of responsive images that I don't think the world needs my extension as well. :)
