### ISSUE TITLE
Composer restricts installation of typo3/cms

### ISSUE THREAD

**Issue by whiteroom** [alexanderschnitzler/fluid-styled-responsive-images#41]
Please update composer.json

Line 21 throws error in composer installation

change `"typo3/cms": "^9.0.0"`
to new: `"typo3/cms-core": "^9.0.0"`

:-)

**Comment by alexanderschnitzler** [comment]
Unfortunately I cannot guarantee that master is actually working. Also I don't find the time to maintain this package any more. Please fork this Extension.

**Comment by whiteroom** [comment]
allright. 
Seems to relate to #37
BTW: tested it intensivley with TYPO3 Version 9.5 and PHP 7.2
everything's fine

**Comment by alexanderschnitzler** [comment]
Hi, I just updated the extension and tagged a 9.5.0 version which is also available on packagist.
https://github.com/alexanderschnitzler/fluid-styled-responsive-images/releases/tag/9.5.0
https://packagist.org/packages/schnitzler/fluid-styled-responsive-images#9.5.0

Would be happy if you'd test the version.
