### ISSUE TITLE
The keyword 'auto' for config.absRefPrefix leads to a corrupt tag

### ISSUE THREAD

**Issue by stephankellermayr** [alexanderschnitzler/fluid-styled-responsive-images#5]
Since TYPO3 7.1 you have the possibility to set _absRefPrefix_ to _auto_, which will lead to a corrupt src-tag: https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#absrefprefix

The problem is that _absRefPrefix_ is inserted without further processing in **Schnitzler\FluidStyledResponsiveImages\Resource\Rendering\ImageRenderer**:

``` php
$url = $this->absRefPrefix . $processedFile->getPublicUrl();
```

As you can see, TYPO3 checks for the keyword _auto_ in **TYPO3\CMS\Frontend\Page\PageGenerator**:

``` php
// calculate the absolute path prefix
if (!empty($tsfe->config['config']['absRefPrefix'])) {
  $absRefPrefix = trim($tsfe->config['config']['absRefPrefix']);
  if ($absRefPrefix === 'auto') {
    $tsfe->absRefPrefix = GeneralUtility::getIndpEnv('TYPO3_SITE_PATH');
  } else {
    $tsfe->absRefPrefix = $absRefPrefix;
  }
} else {
  $tsfe->absRefPrefix = '';
}
```

Perhaps the same check should be applied to **Schnitzler\FluidStyledResponsiveImages\Resource\Rendering\ImageRenderer**.

**Comment by alexanderschnitzler** [comment]
I'd rather directly use the processed value from the TSFE if possible.

**Comment by stephankellermayr** [comment]
Yes, you're right, it should work with:

``` php
$url = $GLOBALS['TSFE']->absRefPrefix . $processedFile->getPublicUrl();
```
