### ISSUE TITLE
No generation for <picture> Tag

### ISSUE THREAD

**Issue by webrealisation** [alexanderschnitzler/fluid-styled-responsive-images#6]
Generation for HTML <picture> Tag ist not included. Would be nice if the could be added in next version.

**Comment by alexanderschnitzler** [comment]
Hi,
I did some research about the purpose of the picture tag and I don't see a need to implement that.

In the following I'd like to explain why. Back then, when different methods for responsive images coexisted, `picture` was one available method for displaying the same image in different sizes dependent on a media query. Nowadays that exact use case is perfectly implemented with `srcset` and `sizes` and the picture element is more for art direction when using different images depending on media queries like showing a cat on small and a dog on big screens.

If talking about the art direction use case, this global typoscript configuration is not the right approach. TYPO3 itself would need to let you add one image element with different sources and let you set the media query along with it. While I think that this would be a great advantage of TYPO3 over other content management systems, I don't see this to be implemented in the near future.
