### ISSUE TITLE
use of this extension?

### ISSUE THREAD

**Issue by Toccamonium** [alexanderschnitzler/fluid-styled-responsive-images#7]
Hi, I installed the extension and included static template into my main template. When I take a look at the rendered html code I don't see any difference without the extension. As rendering definition I'm using fluid_styled_content. What doing I'm wrong?

**Comment by alexanderschnitzler** [comment]
Hey,
by default there is no configuration. I removed the default configuration because in my opinion there is not such thing as a default when it comes to responsive images. Every website has different breakpoints and therefore different image sizes.

This is an example configuration of a working website which has this extension installed:

```
tt_content.textmedia.settings.responsive_image_rendering {
    layoutKey = srcset
    sourceCollection {
        10 {
            width = 1260m
            srcset = 1260w
        }

        20 {
            width = 960m
            srcset = 960w
        }

        30 {
            width = 720m
            srcset = 720w
            sizes = (min-width: 1025px) 660px
        }

        40 {
            width = 640m
            srcset = 640w
        }

        50 {
            width = 360m
            srcset = 360w
        }

        60 {
            width = 320m
            srcset = 320w
            sizes = calc(100vw - 30px)
        }
    }
}
```

Hope I could be of any help here.

**Comment by Toccamonium** [comment]
Thanks, I will try it :)

**Comment by Toccamonium** [comment]
I included your setting into my TS-template. In the TS template browser I see it. As CE I have chosen "text & media" and added a image with "above text". Unfortunately the output didn't change. Did I forget something?

TS-Browser: https://www.dropbox.com/s/a4260fluhk7b8ud/23-01-_2016_15-42-37.png?dl=0
Image setting: https://www.dropbox.com/s/6w6m5797368ev12/23-01-_2016_15-46-38.png?dl=0
Result: https://www.dropbox.com/s/0t9xj6th17oizud/23-01-_2016_15-56-53.png?dl=0

**Comment by alexanderschnitzler** [comment]
Please try this setting: `layoutKey = srcset`

Currently there is no support other than srcset, so the default typoscript of the extension is kind of wrong.

**Comment by Toccamonium** [comment]
Now it's rocking, thanks!

**Comment by alexanderschnitzler** [comment]
Great to hear!
